title: blog
description: simple jekyll blog
baseurl: /blog
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
author:
  name: mhmdilfaj
  email: mhmdilfaj@gmail.com
version: 1.0.0
